@uri = http://localhost:4416


### Not found
GET {{uri}}/not-found

### Hello world
GET {{uri}}/hello

### Hello world
POST {{uri}}/hello

### Hello people
GET {{uri}}/hello/Patrick

### POST - form
POST {{uri}}/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Origin: http://localhost:4416

name=john&password=12345


### POST - JSON
POST {{uri}}/user HTTP/1.1
content-type: application/json
Origin: http://localhost:4416

{
    "name": "sample",
    "age": "999"
}

### embed/HTML
GET {{uri}}/hello.html

### real/HTML
GET {{uri}}/html/hello.txt

### embed/Static - text
GET {{uri}}/static/hello.md

### embed/Static - css
GET {{uri}}/static/hello.css

### embed/Static - js
GET {{uri}}/static/hello.js
