@uri = http://localhost:4416


### Not found
GET {{uri}}/not-found

### Hello world
GET {{uri}}/hello

### Hello people
GET {{uri}}/hello/Patrick

### HTML
GET {{uri}}/hello.html

### HTML #2
GET {{uri}}/html/hello.txt

### Static
GET {{uri}}/static/hello.md

### Static
GET {{uri}}/static/test.css
