@uri = http://localhost:4416


### Not found
GET {{uri}}/not-found

### Hello world
GET {{uri}}/hello

### Hello world
POST {{uri}}/hello

### Hello people
GET {{uri}}/hello/Patrick

### embed/HTML
GET {{uri}}/hello.html

### real/HTML
GET {{uri}}/html/hello.txt

### embed/Static - text
GET {{uri}}/static/hello.md

### embed/Static - css
GET {{uri}}/static/test.css

### embed/Static - js
GET {{uri}}/static/hello.js
